server:
  port: 8082

  
spring:
  redis:
    port: 6379
    host: 101.101.219.90
    password: dlcjf2779!
    
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dlcjf2779\!
    url: jdbc:mysql://101.101.219.90:3306/kubiot?serverTimezone=UTC\&characterEncoding=UTF-8
    username: root