spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dlcjf2779\!
    url: jdbc:mysql://49.50.174.246:3306/kubiot?serverTimezone=UTC\&characterEncoding=UTF-8
    username: vaninside
---

# -- Default spring configuration

spring:
  application:
    name: USER-SERVICE

# -- Eureka client
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://127.0.0.1:8088/eureka/}